### ISSUE TITLE
Not compatible with the version of Windows

### ISSUE THREAD

**Issue by tczee36** [itm4n/PrintSpoofer#6]
Hello,

Was doing TryHackMe room, encountered this error.

![微信截图_20210310000650](https://user-images.githubusercontent.com/10228182/110596855-af0bca00-8134-11eb-9da0-2e32694b2088.png)

**Comment by CybertSys** [comment]
Don't use this version. Use this: https://github.com/dievus/printspoofer

**Comment by hashtaginfosec** [comment]
@CybertSys what did you change? what was the difference that makes your version work? Can you provide the source code if that's okay?

**Comment by yuliang-hk** [comment]
Has the incompatibility issue been resolved?
